import { AIService } from "@/types";

export const aiServices: AIService[] = [
  {
    name: "claude-code",
    displayName: "Claude Code",
    model: "Claude Sonnet 4.5",
    inputPricePerMToken: 3.0,
    outputPricePerMToken: 15.0,
    contextWindow: 200000,
    description: "Anthropic'in resmi CLI aracı",
    category: "cli",
  },
  {
    name: "cursor",
    displayName: "Cursor",
    model: "GPT-4/Claude",
    inputPricePerMToken: 2.5,
    outputPricePerMToken: 10.0,
    contextWindow: 128000,
    description: "AI destekli kod editörü",
    category: "ide",
  },
  {
    name: "windsurf",
    displayName: "Windsurf",
    model: "GPT-4 Turbo",
    inputPricePerMToken: 2.0,
    outputPricePerMToken: 8.0,
    contextWindow: 128000,
    description: "AI kod asistanı",
    category: "ide",
  },
  {
    name: "github-copilot",
    displayName: "GitHub Copilot",
    model: "Codex/GPT-4",
    inputPricePerMToken: 1.5,
    outputPricePerMToken: 6.0,
    contextWindow: 100000,
    description: "GitHub'ın AI çift programcısı",
    category: "ide",
  },
  {
    name: "replit",
    displayName: "Replit AI",
    model: "GPT-3.5/4",
    inputPricePerMToken: 1.0,
    outputPricePerMToken: 4.0,
    contextWindow: 8000,
    description: "Replit'in AI kod asistanı",
    category: "web",
  },
  {
    name: "v0",
    displayName: "v0.dev",
    model: "GPT-4",
    inputPricePerMToken: 2.5,
    outputPricePerMToken: 10.0,
    contextWindow: 32000,
    description: "Vercel'in UI oluşturma aracı",
    category: "web",
  },
  {
    name: "bolt",
    displayName: "Bolt.new",
    model: "GPT-4",
    inputPricePerMToken: 2.0,
    outputPricePerMToken: 8.0,
    contextWindow: 32000,
    description: "StackBlitz'in AI web uygulaması oluşturucusu",
    category: "web",
  },
  {
    name: "gemini-cli",
    displayName: "Gemini CLI",
    model: "Gemini Pro",
    inputPricePerMToken: 0.5,
    outputPricePerMToken: 1.5,
    contextWindow: 1000000,
    description: "Google'ın Gemini CLI aracı",
    category: "cli",
  },
  {
    name: "aider",
    displayName: "Aider",
    model: "GPT-4/Claude",
    inputPricePerMToken: 2.5,
    outputPricePerMToken: 10.0,
    contextWindow: 128000,
    description: "Terminal tabanlı AI çift programcı",
    category: "cli",
  },
];
